import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "./globals.css";

import { UserDataProvider } from "@/context/Usercontext/UserDataContext";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nayi Dukaan",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <UserDataProvider>
          <NavBar />
          {children}
        </UserDataProvider>

      </body>
    </html>
  );
}
